### PR TITLE
Switch to Pegdown processor

### PR DESCRIPTION
**Pull request by elpete**
Switch to Pegdown processor to support tables, links, strikethrough, and other advanced Markdown features.

### CODE REVIEW

**Comment by elpete** [comment]
Yikes!  Just read on the PegDown repo that the project is deprecated.  Let me look in to their suggested alternative, [flexmark](https://github.com/vsch/flexmark-java)

**Comment by lmajano** [comment]
This one looks promising
https://github.com/atlassian/commonmark-java

**Comment by lmajano** [comment]
It is built by atlassian so i will surely think it would be maintained

**Comment by elpete** [comment]
I opened up #3 with the suggested alternative.

**Pull request closed without merging**
